name: PR Quality and Security Check

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          # Ensures we have both PR base and head for the diff
          fetch-depth: 0

      - name: Get Diff
        # Capture the diff of changed files in the PR
        run: git diff origin/main...HEAD > diff.txt

      - name: Display Diff (Debug)
        run: cat diff.txt

      - name: Analyze with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          PROMPT=$(echo "Please review the following code changes for any obvious quality or security issues. Provide a brief report:\n\n$(cat diff.txt)")
          
          # Use jq to construct the JSON request body safely
          jq -n --arg prompt "$PROMPT" '{
            "model": "gpt-3.5-turbo",
            "messages": [
              {
                "role": "system",
                "content": "You are a code reviewer focusing on security and quality."
              },
              {
                "role": "user",
                "content": $prompt
              }
            ],
            "max_tokens": 500,
            "temperature": 0.2
          }' > request.json

          # Debug: print the request
          cat request.json

          # Send the request
          curl https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${OPENAI_API_KEY}" \
            -d @request.json > response.json

      - name: Extract Review Message
        id: extract_message
        run: |
          # Extract the assistant's response content from the JSON
          ASSISTANT_MSG=$(jq -r '.choices[0].message.content' response.json)
          echo "message=$ASSISTANT_MSG" >> $GITHUB_OUTPUT

      - name: Post comment to PR
        env:
          COMMENT: ${{ steps.extract_message.outputs.message }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -f body="$COMMENT"